{
 "title": "Manager",
 "description": "Grafana dashboard for dragonfly manager.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(dragonfly_manager_version,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dragonfly_manager_version{namespace=~\"$namespace\"}) by (git_version, git_commit)",
     "legendFormat": "{{git_version}}-{{git_commit}}"
    }
   ]
  },
  { "title": "GRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "GRPC Global Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(grpc_server_handled_total{grpc_service=\"manager.Manager\",grpc_type=\"unary\",grpc_code=\"OK\",namespace=~\"$namespace\"}[$interval])) + \nsum(rate(grpc_server_handled_total{grpc_service=\"manager.Manager\",grpc_type=\"unary\",grpc_code=\"NotFound\",namespace=~\"$namespace\"}[$interval])) + \nsum(rate(grpc_server_handled_total{grpc_service=\"manager.Manager\",grpc_type=\"unary\",grpc_code=\"PermissionDenied\",namespace=~\"$namespace\"}[$interval])) + \nsum(rate(grpc_server_handled_total{grpc_service=\"manager.Manager\",grpc_type=\"unary\",grpc_code=\"InvalidArgument\",namespace=~\"$namespace\"}[$interval])))\n/ \nsum(rate(grpc_server_started_total{grpc_service=\"manager.Manager\",grpc_type=\"unary\",namespace=~\"$namespace\"}[$interval]))"
    }
   ]
  },
  {
   "title": "GRPC QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_service=\"manager.Manager\",namespace=~\"$namespace\"}[$interval]))"
    }
   ]
  },
  {
   "title": "GRPC request code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_service=\"manager.Manager\",grpc_type=\"unary\",namespace=~\"$namespace\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_method}}/{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Search Scheduler Cluster Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(dragonfly_manager_search_scheduler_cluster_total{namespace=~\"$namespace\"}[$interval])) -\nsum(rate(dragonfly_manager_search_scheduler_cluster_failure_total{namespace=~\"$namespace\"}[$interval])))\n/\nsum(rate(dragonfly_manager_search_scheduler_cluster_total{namespace=~\"$namespace\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Search Scheduler Cluster QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_manager_search_scheduler_cluster_total{namespace=~\"$namespace\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Search Scheduler Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_manager_search_scheduler_cluster_total{namespace=~\"$namespace\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Search Scheduler Cluster Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_manager_search_scheduler_cluster_failure_total{namespace=~\"$namespace\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "REST", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Create Job Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_manager_create_job_success_total{namespace=~\"$namespace\"}[$interval])) /\nsum(rate(dragonfly_manager_create_job_total{namespace=~\"$namespace\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create Job QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_manager_create_job_total{namespace=~\"$namespace\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_manager_create_job_total{namespace=~\"$namespace\"}[$interval]))by(name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create Job Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_manager_create_job_total{namespace=~\"$namespace\"}[$interval]))by(name) - \nsum(rate(dragonfly_manager_create_job_success_total{namespace=~\"$namespace\"}[$interval]))by(name) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "REST Global Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_manager_requests_total{code=~\"[12]..\",namespace=~\"$namespace\"}[$interval]))\n/ \nsum(rate(dragonfly_manager_requests_total{namespace=~\"$namespace\"}[$interval]))"
    }
   ]
  },
  {
   "title": "REST QPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_manager_requests_total{namespace=~\"$namespace\"}[$interval]))"
    }
   ]
  },
  {
   "title": "REST request code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_manager_requests_total{url!=\"/healthy/\",namespace=~\"$namespace\"}[$interval])) by (code, method, url)",
     "legendFormat": "{{method}}-{{url}}-{{code}}"
    }
   ]
  },
  {
   "title": "REST Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(dragonfly_manager_request_duration_seconds_sum{namespace=~\"$namespace\"}[$interval]) * 1000 * 1000 / increase(dragonfly_manager_request_duration_seconds_count{namespace=~\"$namespace\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Golang", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{container=\"manager\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{container=\"manager\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}-resident"
    },
    {
     "expr": "process_virtual_memory_bytes{component=\"manager\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}-virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{container=\"scheduler\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}-bytes_allocated"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{container=\"manager\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}-stack_inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{container=\"manager\",namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}-heap_inuse"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{container=\"manager\",namespace=~\"$namespace\"}[30s])",
     "legendFormat": "{{instance}}-alloc_rate"
    }
   ]
  }
 ]
}